describe('Booking Tiket', () => {

  beforeEach(() => {
    cy.visit('https://testerbud.com/flight-booking-scenarios');
    cy.scrollTo(0.1270)
   })   
   it('Booking tiket', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('.w-100').click()
    cy.get('.list-group > :nth-child(2)').click()
    cy.get('.list-group > :nth-child(3)').click()
    cy.get('[name="cardNumber"]').type('518257012740')
    cy.get('[name="expiryDate"]').type('10-30')
    cy.get('[name="cvv"]').type('159124')
    cy.get('.modal-body > form > .w-100').click()
   })
   it ('Booking tiket dengan tannggal hari sebelumnya', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-23')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('.w-100').click()
   })
   it ('Booking tiket tidak mengisi form returndate', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-23')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('.w-100').click()
   })
   it ('Bokking tidak mengisi passager', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-23')
    cy.get('#passengers').clear()
    cy.get('#travelClass').select('Economy')
    cy.get('.w-100').click()
   })
   it ('Booking tidak memilih kota keberangkatan', () => {
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
   })
   it ('Booking tidak memilih kota tujuan', () => {
    cy.get('#from').select('London')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
   })
   it ('Booking tidak memilih kelas penerbangan', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
   })
   it ('Booking tiket one way', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('#oneWay').click()
    cy.get('.w-100').click()
    cy.get('.list-group > :nth-child(1)').click()
    cy.get('[name="cardNumber"]').type('518257012740')
    cy.get('[name="expiryDate"]').type('10-30')
    cy.get('[name="cvv"]').type('159124')
    cy.get('.modal-body > form > .w-100').click()
   })
   it ('User tidak mengisi cardnumber', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('#oneWay').click()
    cy.get('.w-100').click()
    cy.get('.list-group > :nth-child(1)').click()
    cy.get('[name="expiryDate"]').type('10-30')
    cy.get('[name="cvv"]').type('159124')
    cy.get('.modal-body > form > .w-100').click()
   })
   it ('User tidak mengisi expirydate', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('#oneWay').click()
    cy.get('.w-100').click()
    cy.get('.list-group > :nth-child(1)').click()
    cy.get('[name="cvv"]').type('159124')
    cy.get('.modal-body > form > .w-100').click()
   })
   it ('User tidak mengisi form cvv', () => {
    cy.get('#from').select('London')
    cy.get('#to').select('Tokyo')
    cy.get('#departureDate').type('2025-11-25')
    cy.get('#returnDate').type('2025-11-30')
    cy.get('#passengers').clear()
    cy.get('#passengers').type('2')
    cy.get('#travelClass').select('Economy')
    cy.get('#oneWay').click()
    cy.get('.w-100').click()
    cy.get('.list-group > :nth-child(1)').click()
    cy.get('.modal-body > form > .w-100').click()
   })
});