describe('Register', () => {

  beforeEach(() => {
    cy.visit('https://testerbud.com/practice-forms');
   });
    it('Register Akun Preferred Communication Method dengan Email', () => {
      cy.get('form > :nth-child(1) > .form-select').select('United States')
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(1) > .form-check-input').check()
      cy.get('.btn-primary').click()
      cy.scrollTo(0.1270)
    })
    it('Register Akun Preferred Communication Method dengan Phone', () => {
      cy.get('form > :nth-child(1) > .form-select').select('United States')
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
      cy.scrollTo(0.1270)
    })
    it('Tidak mengisi field negara', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Tidak input nama belakang', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Input tanggal lahir dengan format yang salah ', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('05-09/-1999')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Input tanggal join dengan format yang salah', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24-11-2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Input email dengan format yang salah', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielsloninagmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Tidak memilih kode negara telepon', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Input nomor telepon kurang dari 6 digit', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('8124')
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Mengkosongkan field nomor telepon', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').clear().should('have.value', '');
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
    it('Tidak memilih Preferred Communication Method', () => {
      cy.get(':nth-child(2) > .form-select').select('Mr.')
      cy.get(':nth-child(3) > :nth-child(1) > .form-control').type('Gabriel')
      cy.get(':nth-child(3) > :nth-child(2) > .form-control').type('Slonina')
      cy.get('.react-datepicker__input-container > .form-control').type('1999/09/05')
      cy.get(':nth-child(5) > .form-control').type('24/11/2025')
      cy.get(':nth-child(6) > .form-control').type('gabrielslonina@gmail.com')
      cy.get('.col-md-4 > .form-select').select('+61')
      cy.get('.col-md-8 > .form-control').type('812425521432')
      cy.get('.btn-primary').click()
    })
    it('Tidak mengisi form register', () => {
      cy.get(':nth-child(2) > .form-check-input').check()
      cy.get('.btn-primary').click()
    })
  });